# used to create HostPath volumes, if your cluster is not configured with 
# dynamic volume provisioning.
# for testing purposes only!
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-vol01
  labels:
    app: myapp
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/data/myapp/vol01"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-vol02
  labels:
    app: myapp
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/data/myapp/vol02"