name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Create Container Image Tag for the new Release
        run: |
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} registry.digitalocean.com
          docker pull registry.digitalocean.com/chatx/chatx:${{ github.sha }}
          docker tag registry.digitalocean.com/chatx/chatx:${{ github.sha }} registry.digitalocean.com/chatx/chatx:${{ github.ref_name }}
          docker push registry.digitalocean.com/chatx/chatx:${{ github.ref_name }}

      - name: Get Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          tag_name: ${{ github.ref_name}}
          release_name: ${{ github.ref_name }}
          body: ${{steps.github_release.outputs.changelog}}
          draft: false
          prerelease: false
